### ISSUE TITLE
Make carousel responsive

### ISSUE THREAD

**Issue by anthonyvialleton** [bitriddler/react-items-carousel#1]
Hello, it would be nice to basically push items vertically (on a next row) on small media.

The autogenerated css class don't permit to add extra responsiveness to the component..

Thanks!

**Comment by kareemaly** [comment]
I don't think this is the right library for this, having two rows looks to me more of a grid than a carousel, correct me if I'm wrong 👍will close it for now.

**Comment by route2Dev** [comment]
At first blush, on mobile this seems reasonable. But then would the chevrons be at the top and the bottom? However, having static class names would make writing CSS easier.
