### ISSUE TITLE
 Cannot create styled-component for component: 

### ISSUE THREAD

**Issue by AlaeddineMessadi** [bitriddler/react-items-carousel#14]
There is an issue with Internet Explorer 8 till 11

`Error: Cannot create styled-component for component: .sc-bZQynM. `

I am using :
` "react-items-carousel": "^2.3.0",`

```
    "react": "^16.0.0",
    "react-dom": "^16.0.0"
```

**Comment by kareemaly** [comment]
@AlaeddineMessadi maybe this is related to this issue https://github.com/styled-components/styled-components/issues/1449

This comment suggests a solution for this issue
https://github.com/styled-components/styled-components/issues/1449#issuecomment-420087359

But I think it's not a good idea to add styled-components as a dependency to this package. So I created another issue to remove styled-components and use inline styles instead with inline-styles-prefixer probably...
https://github.com/bitriddler/react-items-carousel/issues/15

**Comment by AlaeddineMessadi** [comment]
@bitriddler This is great! I highly agree with you by using inline styles instead

**Comment by kareemaly** [comment]
I made a temporary fix until I find another approach to `styled-components`. https://github.com/bitriddler/react-items-carousel/issues/15#issuecomment-485387792

Release: https://github.com/bitriddler/react-items-carousel/releases/tag/2.3.4
