### ISSUE TITLE
autoplay option

### ISSUE THREAD

**Issue by amilajack** [bitriddler/react-items-carousel#21]
Is there an option that allows automatically changing the carousel after a certain interval?

**Comment by kareemaly** [comment]
@amilajack Thank you for opening an issue.

Currently this feature is not implemented but I can imagine a lot of use cases that require it. For now I updated the demos to include an example with a custom `autoplay` implementation.

You can find it here: https://bitriddler.github.io/react-items-carousel/

I'll close this issue for now and see first if a custom implementation is flexible enough for all use cases.
