### ISSUE TITLE
Make classNames static

### ISSUE THREAD

**Issue by route2Dev** [bitriddler/react-items-carousel#22]
This is related to #1 - Make carousel responsive. When showing the carousel on mobile, there needs to be some tweaks to the chevron container styles to place the chevron(s) within the image. 

The use case is that for a desktop / tablet we display 3 images. On a phone, we display one image. The numberOfCards prop can be changed by hooking up an event handler to the window.resize event. This works well. However, the chevrons need some additional padding on mobile.

Having static classes (or at least one) on the chevron container would make adding this style via a CSS media query much easier. There may be other places where it would be beneficial to have a static class name as well.

**Comment by kareemaly** [comment]
Hi @route2Dev, you can pass chevrons as react nodes (`leftChevron` and `rightChevron` props) and you can assign class names to them.

```javascript
<ItemsCarousel leftChevron={<button className='...'>...</button>} />
```

Please let me know if this solves your problem

**Comment by emirotin** [comment]
Different need but related. We'd like to put some styling on the DIV generated by the lib, either static class names or props to _add_ our own classes would be handy.

**Comment by kareemaly** [comment]
Released new version with ability to *pass* your own classes
https://github.com/bitriddler/react-items-carousel/releases/tag/2.7.0 

Take a look at this new prop `classes`
