### ISSUE TITLE
on edge - when scrolled to the end

### ISSUE THREAD

**Issue by mehranabi** [bitriddler/react-items-carousel#23]
Hello, Thanks for this work!
Is there any way to know when we scrolled to the end of slider? For example for loading more items?

**Comment by kareemaly** [comment]
Hi! Thanks @mehranabi. Please take a look at this release https://github.com/bitriddler/react-items-carousel/releases/tag/2.5.0

Now you can pass `onActiveStateChange` which will receive this object `{ isLastScroll: Boolean, isFirstScroll: Boolean }` whenever the `activeItemIndex` changes
