### ISSUE TITLE
'width' attribute NaN

### ISSUE THREAD

**Issue by TatsumiSan** [bitriddler/react-items-carousel#26]
Hello,

Using your basic example I got the following error :
 -  Warning: Received NaN for the `width` attribute. If this is expected, cast the value to a string.

Here is what I did : 
- change the children (I did not used createChildren(20) where createChildren is using n => range(n).map(....)
- I removed all the placeholder configurations cause I don't need them

Thank you for your help.

**Comment by TatsumiSan** [comment]
I have some news ;

This time I used the same example hat you used in your demo and :

- I have the same error
- when I remove the placeholder when I access the page where I have the carousel there is no errors but when I ctrl-F5 or F5, the error is displaying.

By the way I'm using
 "react": "^16.3.1",
   "react-dom": "^16.3.1",

**Comment by TatsumiSan** [comment]
![image](https://user-images.githubusercontent.com/19733780/60821356-adda0b00-a1a3-11e9-99fa-286297757cd7.png)

where details.js is my component

**Comment by simofacc** [comment]
PR #24 is related

**Comment by kareemaly** [comment]
Should be fixed by #24 , check new version `2.3.7`
