### ISSUE TITLE
dynamic item carousel is not working

### ISSUE THREAD

**Issue by vairam3360** [bitriddler/react-items-carousel#27]
Trying to do update/delete/add operation on the component inside the item carousel,  but the chevron actions and card navigation works only when right chevron alone present in the screen. Like it works only when index as 0. But if I am in the middle of scroll and do an update/delete/add then chevron actions are not working. and no error logs also. please suggest how to fix this.

**Comment by kareemaly** [comment]
hi @vairam3360 can you please post your code so I can help you. Thanks

**Comment by kareemaly** [comment]
Closing this issue since it has been stale for sometime. Please re-open it if you still have this issue and post a code sample!
