### ISSUE TITLE
Scrolling draggable?

### ISSUE THREAD

**Issue by crscaballero** [bitriddler/react-items-carousel#30]
Hi, I was looking in the documentation about this, but I couldn't find it, is there any way for make the items draggable?

thanks

**Comment by kareemaly** [comment]
@crscaballero Hi! previously no, but I just released a new version with swipe functionality, please take a look and tell me if you have any issues :)
https://github.com/bitriddler/react-items-carousel/releases/tag/2.4.0

**Comment by crscaballero** [comment]
Amazing, thank you so much!

**Comment by hungdev** [comment]
im using latest version, but i cant drag, swipe to scroll
https://codesandbox.io/s/objective-lederberg-xygkv?file=/src/App.js:681-693
@kareemaly
