### ISSUE TITLE
Looping items

### ISSUE THREAD

**Issue by imlastrebor** [bitriddler/react-items-carousel#35]
Hello, is it possible to loop carousel items? If it's not possible at the moment is it hard to add this feature?

**Comment by kareemaly** [comment]
Hi @imlastrebor, I made a new release that includes this feature, please take a look https://github.com/bitriddler/react-items-carousel/releases/tag/2.8.0

Also take a look at the demo https://bitriddler.github.io/react-items-carousel/ and the limitations of this feature https://github.com/bitriddler/react-items-carousel#infinite-loop-limitations
