### ISSUE TITLE
Invalid prop `children` of type `object`

### ISSUE THREAD

**Issue by khangahs** [bitriddler/react-items-carousel#61]
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to index.js:1 `t`, expected an array.
    in t
  | console.<computed> | @ | index.js:1
-- | -- | -- | --
  | printWarning | @ | checkPropTypes.js:20
  | checkPropTypes | @ | checkPropTypes.js:82
  | validatePropTypes | @ | react.development.js:1666
  | createElementWithValidation | @ | react.development.js:1755
  | value | @ | react-items-carousel.js:1
  | finishClassComponent | @ | react-dom.development.js:17160
  | updateClassComponent | @ | react-dom.development.js:17110
  | beginWork | @ | react-dom.development.js:18620
  | beginWork$1 | @ | react-dom.development.js:23179
  | performUnitOfWork | @ | react-dom.development.js:22154
  | workLoopSync | @ | react-dom.development.js:22130
  | performSyncWorkOnRoot | @ | react-dom.development.js:21756
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21188
  | updateContainer | @ | react-dom.development.js:24373
  | (anonymous) | @ | react-dom.development.js:24758
  | unbatchedUpdates | @ | react-dom.development.js:21903
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:24757
  | render | @ | react-dom.development.js:24840
  | ./src/index.js | @ | index.js:6
  | __webpack_require__ | @ | bootstrap:784
  | fn | @ | bootstrap:150
  | 1 | @ | theme.js:1
  | __webpack_require__ | @ | bootstrap:784
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous) | @ | main.chunk.js:1

**Comment by crscaballero** [comment]
Not sure if would be the same situation, but I had this error when I print the children into `<ItemsCarousel>` 1 by one, I've solved creating a function which save the children in one array, and once the array is completed, return the content at the same time into `<ItemsCarousel>`
