### ISSUE TITLE
How to always show both left and right chevrons but with a disabled status when there is no item to scroll?

### ISSUE THREAD

**Issue by eliu091** [bitriddler/react-items-carousel#63]
Hi there, I have set alwaysShowChevrons as true but want to set the chevron with.a disabled status. Is there anyway to do that? Thank you!

**Comment by kareemaly** [comment]
Hi @eliu091 , you can use `leftChevron` and `rightChevron` and provide the disable functionality yourself, e.g.
```javascript
leftChevron={<button disabled={activeItemIndex === 0}>Left Arrow</button>}
```
