### ISSUE TITLE
Carousel Responsiveness

### ISSUE THREAD

**Issue by iyanushow** [bitriddler/react-items-carousel#72]
Is there a way to implement responsiveness in react-item-carousel responsiveness, I need the number of cards prop to reduce at different breakpoints

**Comment by AbeEstrada** [comment]
You can use `useResponsiveValue` from this package [`@theme-ui/match-media`](https://github.com/system-ui/theme-ui/tree/develop/packages/match-media)

```js
const numberOfCards = useResponsiveValue([1, 2, 3]);
```

**Comment by iyanushow** [comment]
thank you 
Issue has been resolved
